# Generated by Django 3.2 on 2021-04-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Садоводческий коллектив',
                'verbose_name_plural': 'Садоводческие коллективы',
            },
        ),
        migrations.CreateModel(
            name='Type_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип адреса',
                'verbose_name_plural': 'Типы адресов',
            },
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Улица')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.type_address', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='DeleviryDistricts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Район')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Район доставки',
                'verbose_name_plural': 'Районы доставки',
            },
        ),
    ]
