# Generated by Django 3.2 on 2021-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('code1C', models.CharField(max_length=11, verbose_name='Код 1С')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.AlterField(
            model_name='delevirydistricts',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='gardens',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='type_address',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип'),
        ),
    ]
