# Generated by Django 3.2 on 2021-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210417_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delevirydistricts',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='gardens',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='streets',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='type_address',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тип'),
        ),
    ]
