# Generated by Django 3.2 on 2021-04-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code1C',
            field=models.CharField(blank=True, max_length=11, verbose_name='Код 1С'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
    ]
