# Generated by Django 3.2 on 2021-04-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('company', 'Компания'), ('private_person', 'Частное лицо')], default='private_person', max_length=15, null=True, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_play',
            field=models.CharField(choices=[('cash', 'Наличный'), ('cashless', 'Безналичный')], default='cash', max_length=15, null=True, verbose_name='Тип оплаты'),
        ),
    ]
