# Generated by Django 3.2 on 2021-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210429_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.district', verbose_name='Район'),
        ),
    ]
