# Generated by Django 3.2 on 2021-04-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delevirydistricts',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Gardens',
        ),
        migrations.RemoveField(
            model_name='streets',
            name='type',
        ),
        migrations.DeleteModel(
            name='DeleviryDistricts',
        ),
        migrations.DeleteModel(
            name='Streets',
        ),
        migrations.DeleteModel(
            name='Type_address',
        ),
    ]
