# Generated by Django 3.2 on 2021-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20210430_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
