# Generated by Django 3.2 on 2021-05-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210503_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.driver', verbose_name='Водитель'),
        ),
    ]
