# Generated by Django 3.2 on 2021-05-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0018_alter_client_type_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
