# Generated by Django 3.2 on 2021-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20210518_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта'),
        ),
    ]
