# Generated by Django 3.2 on 2021-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='plane',
            field=models.IntegerField(blank=True, default=80, max_length=3, verbose_name='План заявок в день'),
        ),
    ]
