# Generated by Django 3.2 on 2021-06-22 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_driver_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
