# Generated by Django 3.2 on 2021-06-22 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_client_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
