# Generated by Django 3.2 on 2021-07-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20210714_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
