# Generated by Django 3.2 on 2021-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_positions_min_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Телефон(WhatsApp)'),
        ),
    ]
