# Generated by Django 3.2 on 2021-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number1С',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер 1С'),
        ),
    ]
