# Generated by Django 3.2 on 2021-04-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_order_number1с'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabluarorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabulars', to='documents.order', verbose_name='Ссылка'),
        ),
    ]
