# Generated by Django 3.2 on 2021-04-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210422_1051'),
        ('documents', '0005_alter_tabluarorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabluarorders',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_name', to='common.positions', verbose_name='Номенклатура'),
        ),
    ]
