# Generated by Django 3.2 on 2021-04-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_tabluarorders_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabluarorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulars', to='documents.order', verbose_name='Ссылка'),
        ),
    ]
