# Generated by Django 3.2 on 2021-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_tabluarorders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_play',
            field=models.CharField(choices=[('cash', 'Наличный'), ('cashless', 'Перечисление')], default='cash', max_length=15, null=True, verbose_name='Тип оплаты'),
        ),
    ]
