# Generated by Django 3.2 on 2021-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_order_type_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('completed', 'Завершен'), ('postponed', 'Отложен')], default='new', max_length=15, null=True, verbose_name='Тип оплаты'),
        ),
    ]
