# Generated by Django 3.2 on 2021-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('new', 'Новый'), ('completed', 'Завершен'), ('postponed', 'Отложен')], default='new', max_length=15, null=True, verbose_name='Статус заказа'),
        ),
    ]
