# Generated by Django 3.2 on 2021-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned_container',
            field=models.CharField(blank=True, default=0, max_length=3, verbose_name='Возвращено бутылей'),
        ),
    ]
