# Generated by Django 3.2 on 2021-05-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_order_returned_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_bot',
            field=models.BooleanField(blank=True, default=False, verbose_name='Чат-бот'),
        ),
        migrations.AddField(
            model_name='order',
            name='new_client',
            field=models.BooleanField(blank=True, default=False, verbose_name='Новый клиент'),
        ),
    ]
