# Generated by Django 3.2 on 2021-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='not_load_1C',
            field=models.BooleanField(blank=True, default=False, verbose_name='Не грузить в 1С'),
        ),
    ]
