# Generated by Django 3.2 on 2021-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_order_not_load_1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='not_load_1C',
        ),
        migrations.AddField(
            model_name='order',
            name='load_1C',
            field=models.BooleanField(blank=True, default=True, verbose_name='Грузить в 1С'),
        ),
    ]
