# Generated by Django 3.2 on 2021-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20210527_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_dev',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
