# Generated by Django 3.2 on 2021-06-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20210603_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_dev',
            field=models.DateField(blank=True, null=True, verbose_name='Дата клиента'),
        ),
    ]
