# Generated by Django 3.2 on 2021-06-03 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_order_date_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата от'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
    ]
