# Generated by Django 3.2 on 2021-06-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_dev',
            field=models.DateField(null=True, verbose_name='Дата клиента'),
        ),
    ]
