# Generated by Django 3.2 on 2021-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_order_date_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attention',
            field=models.BooleanField(blank=True, default=False, verbose_name='Внимание'),
        ),
    ]
