# Generated by Django 3.2 on 2021-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_order_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_dev',
            field=models.DateField(null=True, verbose_name='Дата доставки'),
        ),
    ]
